services:
  - type: web
    name: clausegpt-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn llm-query-retrieval.app.main:app --host 0.0.0.0 --port $PORT
    plan: free
